### ISSUE TITLE
安装时报错，提示nginx缺少ssl

### ISSUE THREAD

**Issue by colinshin** [dafengzhen/youdeyiwu-frontend#284]
ubuntu 22.04
`
[+] Running 21/20  ✔ Network youdeyiwu-backend       Created        0.1s
 ✔ Network youdeyiwu-frontend                            Created           0.1s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-backend-keys"     Created 0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-oss"              Created      0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-frontend-icons"   Created     0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-nginx"            Created    0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-backend-logs"     Created     0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-backend-indexs"   Created   0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-cache"            Created     0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-db"               Created      0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-oss-events"       Created   0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-frontend-images"  Created  0.0s
 ✔ Volume "youdeyiwu-hosting_youdeyiwu-mq"               Created     0.0s
 ✔ Container youdeyiwu-mq                                Created  0.5s
 ✔ Container youdeyiwu-db                                Created        0.5s
 ✔ Container youdeyiwu-cache                             Created      0.5s
 ✔ Container youdeyiwu-cache-cli                         Created       0.1s
 ✔ Container youdeyiwu-oss                               Created        0.1s
 ✔ Container youdeyiwu-oss-cli                           Created      0.1s
 ✔ Container youdeyiwu-server                            Created        0.1s
 ✔ Container youdeyiwu-web                               Created        0.1s
 ⠋ Container youdeyiwu-nginx                             Creating   0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/youdeyiwu-hosting/nginx/ssl

`

**Comment by dafengzhen** [comment]
感谢反馈

已修复缺少的文件夹，请尝试重新拉取项目：

```bash
cd youdeyiwu-hosting
```

```bash
git pull
```

**Comment by colinshin** [comment]
好了，问题但我关了
