### ISSUE TITLE
请问是没有适配PC端吗  

### ISSUE THREAD

**Issue by Yakumo-Yukari** [dafengzhen/youdeyiwu-frontend#363]
感觉前端怪怪的 就像是移动端的UI在PC端直接放大的感觉

**Comment by dafengzhen** [comment]
有适配 PC 端，默认是以 PC 端开发的

看上去页面正常，我当前环境是：
1920 x 1080，Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

是哪里比较怪吗

**Comment by dafengzhen** [comment]
对比其他网站，确实整体稍微大了些

后续修改一下
